# These are supported funding model platforms

github: [Harjotraith04]
# patreon: # your-patreon-username
# open_collective: # your-opencollective-username
# ko_fi: # your-kofi-username
# tidelift: # npm/package-name
# community_bridge: # your-communitybridge-project
# liberapay: # your-liberapay-username
# issuehunt: # your-issuehunt-username
# otechie: # your-otechie-username
# lfx_crowdfunding: # your-lfx-crowdfunding-project
# custom: ['https://your-custom-url.com']
